name: Rebase main-dev branch

on:
  push:
    branches: ["main-dev"]
  pull_request:
    branches: ["main-dev"]
# test
permissions:
  contents: write

jobs:

  versioning:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Test for versioning
      run: echo "Versioning passed"


  rebase:
    name: Rebase from main into main-dev
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
