name: Rebase main-dev branch

# test

on:
  pull_request:
    types:
      - closed
      
jobs:

  versioning:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Test for versioning
      run: echo "Versioning passed"

  rebase:
    name: Rebase from main into main-dev
    needs: versioning
    if: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'main-dev' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.mytoken }}
          fetch-depth: 0

      - name: Rebase main into main-dev
        uses: cirrus-actions/rebase@1.8
        env:
          GITHUB_TOKEN: ${{ secrets.mytoken }}