name: Release

on:
  push:
    branches: ["main"]
  

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  versioning:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3

    - run: npm install --save-dev @semantic-release/changelog @semantic-release/exec @semantic-release/git conventional-changelog-eslint semantic-release && npx semantic-release

    - name: Checkout Repository
      uses: actions/checkout@v3

    
    - uses: robinraju/release-downloader@v1.8
      with:
        latest: true
        fileName: "*"
        out-file-path: "download_assets"
        tarBall: true
        zipBall: true

    - name: Calculate Hashes
      id: calculate_hashes
      run: |
          source_zip=$(find $GITHUB_WORKSPACE/download_assets -name "*.zip")
          source_zip_hash=$(sha256sum "$source_zip" | awk '{print $1}')
          source_tar=$(find $GITHUB_WORKSPACE/download_assets -name "*.tar.gz")
          source_tar_hash=$(sha256sum "$source_tar" | awk '{print $1}')
          echo "::set-output name=source_zip_hash::$source_zip_hash"
          echo "::set-output name=source_zip_hash::$source_zip_hash"

    - name: Get latest release
      id: get_latest_release
      run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.SEMANTIC_RELEASE_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          echo "::set-output name=release_id::$(echo "$response" | jq -r '.id')"

    - name: Edit Release
      uses: irongut/EditRelease@v1.2.0
      with:
        token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        id: ${{ steps.get_latest_release.outputs.release_id }}
        prerelease: false
        replacebody: false
        body: |
            ## Hashes
            * Source code(zip) - `${{ steps.calculate_hashes.outputs.source_zip_hash }}` 
            * Source code(tar.gz) - `${{ steps.calculate_hashes.outputs.source_zip_hash }}`
          

  rebase:
    name: Rebase from main into main-dev
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
          persist-credentials: false
      
      - name: Perform Rebase
        run: |
          git checkout main-dev
          git rebase origin/main

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.REBASE }}
          branch: main-dev
          unprotect_reviews: True
          force: True

####