name: Release

on:
  push:
    branches: ["main"]
  release:
    types: [published]
  

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  versioning:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3

    - run: npm install --save-dev @semantic-release/changelog @semantic-release/exec @semantic-release/git conventional-changelog-eslint semantic-release && npx semantic-release

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Edit Release
      uses: irongut/EditRelease@v1.2.0
      with:
        token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        id: ${{ github.event.release.id }}
        name: "Beta"
        prerelease: true
        body: "This is a pre-release version for testing purposes."   
          

  rebase:
    name: Rebase from main into main-dev
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
          persist-credentials: false
      
      - name: Perform Rebase
        run: |
          git checkout main-dev
          git rebase origin/main

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.REBASE }}
          branch: main-dev
          unprotect_reviews: True
          force: True

####