name: Release

on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Release

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  versioning:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Test for versioning
      run: echo "Versioning passed"

  rebase:
    name: Rebase from main into main-dev
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
          persist-credentials: false

      # - name: Calculate file hashes
      #   run: |
      #     # echo "| File Name | Hash |" > hashes.md
      #     # echo "| --- | --- |" >> hashes.md
      #     # find . -type f -not -path './.git/*' -exec sh -c 'echo "| $(realpath --relative-to=. {}) | $(sha256sum {} | awk "{print \$1}") |"' \; >> hashes.md
      #     echo '## Assets' >> release_notes.md
      #     find . -type f -not -path './.git/*' -not -name 'release_notes.md' -exec sh -c 'echo "$(basename {}) : $(sha256sum {} | awk "{print \$1}")"' \; >> release_notes.md

      - name: Generate release notes
        run: |
          echo '<details>\n' >> release_notes.md
          echo '<summary>Assets</summary>' >> release_notes.md
          echo "" >> release_notes.md
          find . -type f -not -path './.git/*' -not -name 'release_notes.md' -exec sh -c 'echo "* $(realpath --relative-to=. {}) : \`$(sha256sum {} | awk "{print \$1}")\`"' \; >> release_notes.md
          echo '</details>' >> release_notes.md

      - name: Upload docs to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REBASE }}
        with:
          file: release_notes.md
          update_latest_release: true   
      
      - name: Perform Rebase
        run: |
          git checkout main-dev
          git rebase origin/main

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.REBASE }}
          branch: main-dev
          unprotect_reviews: True
          force: True

          

  # add comment
  # comment
  ###  ####