name: Release

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}
  
permissions:
  contents: write
  pages: write
  id-token: write

jobs:

   publish_wasm:
    name: WASM Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'  
    - run: echo "${{github.actor}}"
    
    # - name: Trigger Wasmer.io CLI
    #   run: curl https://get.wasmer.io -sSfL | sh
      
    # - name: Trigger Wasmer.io CLI
    #   run: |
    #     curl https://get.wasmer.io -sSfL | sh
    #     source ~/.wasmer/wasmer.sh
    #     wasmer login "${{ secrets.WASMER_TOKEN }}"
    #     wasmer publish
