name: Release

on:
  push:
    branches: ["main"]
  
permissions:
  contents: write
  pages: write
  id-token: write

jobs:

   publish_wasm:
    name: WASM Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'  
    - run: git submodule update --init --recursive
    
    - name: Trigger Wasmer.io CLI
      run: curl https://get.wasmer.io -sSfL | sh
      
    - name: Source
      run: source ~/.wasmer/wasmer.sh
    
    - name: Login and publish
      run: |
        wasmer login --token "${{ secrets.WASMER_TOKEN }}"
        wasmer publish
