name: Release

on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Release

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  versioning:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Test for versioning
      run: echo "Versioning passed"

  rebase:
    name: Rebase from main into main-dev
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'   
      
      - name: Perform Rebase
        run: |
          git checkout main-dev
          git rebase origin/main

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.REBASE }}
          branch: main-dev
          unprotect_reviews: True
          force: True

      - name: Create folder
        run: mkdir -p build/docs/html/

      - name: Copy assets
        run: cp -r assets build/docs/html/

      - name: Compress assets
        run: tar -czvf docs.tar.gz build/docs/html/

      - name: Calculate file hashes
        run: |
          find . -type f -exec sha256sum {} \; | awk '{print $2 " " $1}' > hashes.txt
          cat hashes.txt

      - name: Upload docs to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REBASE }}
        with:
          file: hashes.txt
          update_latest_release: true

      

      # - name: Calculate hash 
      #   uses: MCJack123/ghaction-generate-release-hashes@v3
      #   with:
      #     hash-type: sha256
      #     file-name: hashes.txt
      #   env:
      #     BUILD_TYPE: Release

      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: Asset Hashes
          path: hashes.txt
          
          

  # add comment
  # comment
  ###  ####